### ISSUE TITLE
 `HtmlContainer::executeAsyncScript` kills the client if the control which uses the HtmlContainer is not yet attached to a panel.

### ISSUE THREAD

**Issue by hyyan** [DwcJava/engine#73]
This is more of a question than a bug report.

**How to use the `HtmlContainer` to build a custom control?**

If we were able to use the `BBjHTMLView` directly then it would be up to the custom control to queue the executed scripts and wait until the `BBjHTMLView` is created then execute them in the client but this is not possible outside the `dwcj` package.

In case of  `HtmlContainer::executeAsyncScript`, probably it easy to implement this logic in `HtmlContainer` , currently only the last executed script is re-applied in `catchup` 
In case of `HtmlContainer::executeScript` this can be an issue because a returned value is expected from the client. Adding the scripts to queue and returning `null`  does not seem to be correct.

**Should we throw an exception in case the `BBjHTMLView` is not created and force the developer to add the custom control as early as possible? What would be the best approach here ? or I'm missing something?**

The debug log shows the following:

```
[23:28:58.853+0100] SYSERR  com.basis.rmi.RMICommException: Exception caught
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.client.rmi.BBjRMIConnection.sendSyncMessage(BBjRMIConnection.java:4)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.client.rmi.BBjRMIConnection.sendSyncCommand(BBjRMIConnection.java:30)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.rmi.ServerRMIConnection.access$101(ServerRMIConnection.java:80)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.rmi.ServerRMIConnection$SyncCallStrategy.doCall(ServerRMIConnection.java:1)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.rmi.OnDemandBatchStrategy.syncCall(OnDemandBatchStrategy.java:52)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.rmi.OnDemandBatchStrategy.sendSyncCommand(OnDemandBatchStrategy.java:77)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.rmi.ServerRMIConnection.sendSyncCommand(ServerRMIConnection.java:24)
[23:28:58.854+0100] SYSERR  	at com.basis.rmi.RMIStub.sendRequestCommand(RMIStub.java:276)
[23:28:58.854+0100] SYSERR  	at com.basis.rmi.StubMethodInvoker.request(StubMethodInvoker.java:43)
[23:28:58.854+0100] SYSERR  	at com.basis.rmi.InstanceProxy.request(InstanceProxy.java:69)
[23:28:58.854+0100] SYSERR  	at com.basis.rmi.shellgen.com_basis_bbj_web_app_server_console_MiniConsoleBridgeShell.terminate(Unknown Source)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.console.MiniConsole.terminate(MiniConsole.java:117)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.channel.ChannelZero.closeChannelAndConsole(ChannelZero.java:23)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.processor.j.a(j.java:522)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.processor.j.a(j.java:286)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.bw.a(bw.java:1563)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.bw.d(bw.java:2446)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.bw.run(bw.java:829)
[23:28:58.854+0100] SYSERR  	at com.basis.util.common.BasisThread.run(BasisThread.java:75)
[23:28:58.854+0100] SYSERR  Caused by: com.basis.startup.type.BBjException: Channel has been terminated
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.comm.s.handleInputTerminatedWaitForMessage(s.java:1)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.client.comm.StubAgent.waitForSynchMessage(StubAgent.java:7)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.client.comm.StubAgent.sendMessageToImplementation(StubAgent.java:12)
[23:28:58.854+0100] SYSERR  	at com.basis.bbj.client.rmi.BBjRMIConnection.sendSyncMessage(BBjRMIConnection.java:22)
[23:28:58.854+0100] SYSERR  	... 18 more
[23:28:58.854+0100] SYSERR  Socket already closed trying to cleanly terminate
[23:28:58.854+0100] INFO    ThinClient:/0.0.0.0:2003 [/127.0.0.1:60488] client terminated
[23:28:58.870+0100] INFO    ThinClient:/0.0.0.0:2003 [/127.0.0.1:63584] socket connection (1 total connections)
[23:28:58.886+0100] INFO    ThinClient:/0.0.0.0:2003 [/127.0.0.1:63584] User 'nobody' successfully logged in.
[23:28:59.046+0100] INFO    DWC components=https://s3-eu-west-1.amazonaws.com/cdn.bbx.kitchen/next
[23:36:26.697+0100] SYSOUT  Memory: [free=236735592,total=544210944,max=4169138176,used=307475352,timestamp=2023-01-03 23:36:26]
[23:51:26.705+0100] SYSOUT  Memory: [free=229105808,total=544210944,max=4169138176,used=315105136,timestamp=2023-01-03 23:51:26]
```

The following code can be tested in the `annotation` branch:

```css
/* resources/css/style.css */
.app-panel .BBjWindow > .BBjPanel {
  overflow-y: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap: 1rem;
  height: 100%;
}
```

```java
package org.demo;

import org.dwcj.App;
import org.dwcj.annotations.AppTheme;
import org.dwcj.annotations.AppTitle;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;

@AppTheme("dark")
@AppTitle("QR Code Generator")
@InlineStyleSheet(value = "css/style.css", local = true, id = "app-bundle")
public class Playground extends App {

  @Override
  public void run() throws DwcException {
    AppPanel panel = new AppPanel();
    panel.addClassName("app-panel");

    String defaultValue = "https://dwcj.org/";

    QRCode qr = new QRCode(defaultValue);
    qr.setSize(200);
    qr.setColor(Color.ORANGE);

    TextBox editBox = new TextBox();
    editBox.setText(defaultValue);
    editBox.setExpanse(TextBox.Expanse.LARGE);
    editBox.setAttribute("placeholder", "Enter a value");
    editBox.onEditModify((e) -> {
      qr.setValue(editBox.getText());
    });

    panel.add(qr, editBox);
  }
}
```

```java
package org.demo;

import java.awt.Color;
import java.util.UUID;

import org.dwcj.annotations.Attribute;
import org.dwcj.annotations.JavaScript;
import org.dwcj.controls.AbstractControl;
import org.dwcj.controls.htmlcontainer.HtmlContainer;
import org.dwcj.controls.panels.AbstractDwcjPanel;

/**
 * QRCode Generator using Shoelace QRCode component
 * 
 * @author Hyyan Abo Fakher
 */
@JavaScript(id = "shoelace-qr-code", url = "https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.87/dist/shoelace.js", attributes = {
    @Attribute(name = "type", value = "module")
})
final public class QRCode extends AbstractControl {
  private HtmlContainer hv;
  private final String uuid = UUID.randomUUID().toString().substring(0, 8);
  private String value;
  private int size = 65;
  private Color color = Color.BLACK;

  public QRCode() {
    super();
  }

  public QRCode(String value) {
    super();
    this.value = value;
  }

  /**
   * Get the UUID of the toast.
   * 
   * @return the UUID of the toast.
   */
  public String getUUID() {
    return uuid;
  }

  /**
   * Get the value of the QRCode
   * 
   * @return the value of the QRCode
   */
  public String getValue() {
    return value;
  }

  /**
   * Set the value of the QRCode
   * 
   * @param value the value of the QRCode
   */
  public QRCode setValue(String value) {
    this.value = value;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('value', '" + value + "')");
    return this;
  }

  /**
   * Get the size of the QRCode
   * 
   * @return the size of the QRCode
   */
  public int getSize() {
    return size;
  }

  /**
   * Set the size of the QRCode
   * 
   * @param size the size of the QRCode
   */
  public QRCode setSize(int size) {
    this.size = size;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('size', '" + size + "')");
    return this;
  }

  /**
   * Get the color of the QRCode
   * 
   * @return the color of the QRCode
   */
  public Color getColor() {
    return color;
  }

  /**
   * Set the color of the QRCode
   * 
   * @param color the color of the QRCode
   */
  public QRCode setColor(Color color) {
    this.color = color;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('fill', '" + toHexString(color) + "')");
    return this;
  }

  /**
   * Create the control
   * 
   * @param p the parent panel
   */
  protected void create(AbstractDwcjPanel p) {
    super.create(p);

    hv = new HtmlContainer("<sl-qr-code value='" + value + "' size='" + size
        + "' fill='" + toHexString(color) + "'></sl-qr-code>");
    hv.setAttribute("data-hv", getUUID());
    hv.setTabTraversable(false);
    hv.setFocusable(false);

    // add the control to the parent panel
    p.add(hv);
  }

  /**
   * Convert a color to a hex string
   * 
   * @param color the color to convert
   * @return
   */
  private String toHexString(Color color) {
    return String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
  }
}
```

**Comment by StephanWald** [comment]
the scripts etc still need to be included in the catchUp. This is a structural issue for a few more controls. We did catchup for the "mundane" attributes but not (yet) for everything
